//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventRegistrationApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string Email { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public Nullable<int> Age { get; set; }
        public string Phone { get; set; }
    }
}
