//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventRegistrationApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int Id { get; set; }
        public Nullable<int> GuestNumber { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public string EventName { get; set; }
        public string Email { get; set; }
    }
}
